version: '3.9'

services:
#  main:
#    container_name: api
#    build:
#      context: .
#    env_file:
#      - .production.env
#    volumes:
#      - .:/app
#      - /app/node_modules
#    ports:
#      - 3001:3001
#      - 9229:9229
#    command: npm run start:debug
#    depends_on:
#      - postgres
#    restart: always
  postgres:
    container_name: postgres
    image: postgres:13.4
    env_file:
      - .development.env
    environment:
      PG_DATA: /var/lib/postgresql/data
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:

